---
- hosts: all
  become: yes
  roles:
  - { role: azavea.postgresql }  
  - { role: azavea.postgis }  
  tasks: 
  - name: apt get update
    apt: update_cache=yes
  - name: install git
    apt: name=git state=present
  - name: install osm2pgsql
    apt: name=osm2pgsql state=present
  - name: "get vector datasource"
    become_user: vagrant
    git: repo=https://github.com/mapzen/vector-datasource force=yes update=yes dest=~/vector-datasource accept_hostkey=True